let que = document.createElement("script");
que.src = "xql/que.js"; 
document.head.appendChild(que); 
let query = document.createElement("script");
query.src = "xql/query.js"; 
document.head.appendChild(query); 
let hexe = document.createElement("script");
hexe.src = "xql/hex.js"; 
document.head.appendChild(hexe); 
let xcon = document.createElement("script");
xcon.src = "xql/xcon.js"; 
document.head.appendChild(xcon); 
let css = document.createElement("link");
css.href = "xql/hex.css"; 
css.rel = "stylesheet"; 
document.head.appendChild(css); 